[project]
name = "fasthtml-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "monsterui>=1.0.19",
    "python-dotenv>=1.1.0",
    "python-fasthtml>=0.12.14",
]
